name: ElectricSpawners
version: ${project.version}
author: mrCookieSlime
website: http://thebusybiscuit.github.io/
depend: [CS-CoreLib, Slimefun]

api-version: 1.13

main: me.mrCookieSlime.ElectricSpawners.ElectricSpawners